### ISSUE TITLE
Crash: Starting a service intent

### ISSUE THREAD

**Issue by PankajS24** [verloop/android-sdk#6]
`Fatal Exception: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=io.verloop.sdk.VerloopService }: app is in background uid UidRecord{82ceb30 u10a552 CAC  bg:+17m5s620ms idle procs:1 seq(0,0,0)}
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3388)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3527)
       at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5410)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5318)
       at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:57)
       at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:5369)
       at android.app.ActivityThread.access$3800(ActivityThread.java:232)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7710)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)`

**Comment by raghav39** [comment]
We have made some minor change in the way we initialise our service in the version `1.0.8-rc01`. We are also exploring the jobScheduler to replace our service but right now try this fix.

**Comment by NancyM6** [comment]
I am facing the same issue. @PankajS24 Has this issue been resolved?

**Comment by riteshkarmare94** [comment]
@raghav39 @shobhitic  Any update on this issue? I'm facing the same issue. 
As we don't want to display notifications to our users by starting foreground service.

Please update!

**Comment by kaushalbhardwaj** [comment]
Facing the same issue with 1.0.8 version of the sdk

**Comment by sushilk55** [comment]
@raghav39 Any update on the permanent fix?

**Comment by viju-zivame** [comment]
@raghav39 Is this issue resolved?

**Comment by ravipetlur** [comment]
Please test this with the latest build.
